"""
TouchDesigner Setup Script: Standard Recital
==============================================
Auto-generated by the Production Event Template System.

HOW TO USE:
  1. Open TouchDesigner
  2. Create a new Text DAT (right-click > DAT > Text)
  3. Paste this entire script into the Text DAT
  4. Right-click the Text DAT > Run Script
  5. The script will create all operators in the /project1 container

The script builds:
  - Video Device In TOPs for each camera input
  - A Switch TOP for live camera switching
  - OSC In DAT for receiving messages from the Production Hub
  - Cue handler logic for automated switching
  - Render output pipeline

Event type: standard_recital
"""


# ============================================================
# CAMERA INPUT SETUP
# ============================================================

def setup_cameras():
    """Create Video Device In TOPs for each camera."""
    project = op('/project1')

    # cam1: wide shot from front_center
    cam1 = project.create(videodeviceinTOP, "cam1")
    cam1.par.device = 0
    cam1.par.resolutionw = 1920
    cam1.par.resolutionh = 1080
    cam1.par.rate = 30
    cam1.nodeX = 0
    cam1.nodeY = 0
    cam1.comment = "wide shot - front_center"

    # cam2: medium shot from stage_left
    cam2 = project.create(videodeviceinTOP, "cam2")
    cam2.par.device = 1
    cam2.par.resolutionw = 1920
    cam2.par.resolutionh = 1080
    cam2.par.rate = 30
    cam2.nodeX = 250
    cam2.nodeY = 0
    cam2.comment = "medium shot - stage_left"

    print("Created 2 camera inputs")
    return [cam1, cam2]


# ============================================================
# VIDEO SWITCH SETUP
# ============================================================

def setup_switch(cameras):
    """Create a Switch TOP to cut between camera inputs."""
    project = op('/project1')

    switch = project.create(switchTOP, "video_switch")
    switch.par.index = 0  # Default to cam1
    switch.nodeX = 250
    switch.nodeY = -200
    switch.comment = "Main video switch - controlled via OSC"

    # Connect all camera inputs to the switch
    for i, cam in enumerate(cameras):
        cam.outputConnectors[0].connect(switch)

    print(f"Video switch created with {len(cameras)} inputs (default: input 0)")
    return switch



# ============================================================
# OSC INPUT SETUP
# ============================================================

def setup_osc():
    """Create OSC In DAT for receiving cue triggers."""
    project = op('/project1')

    # OSC input for receiving cue commands
    osc_in = project.create(oscInDAT, "osc_input")
    osc_in.par.port = 12000
    osc_in.par.active = True
    osc_in.nodeX = 500
    osc_in.nodeY = 200
    osc_in.comment = "Receives OSC from Production Hub (/td prefix stripped)"

    print(f"OSC input listening on port 12000")
    return osc_in



# ============================================================
# CUE HANDLER
# ============================================================

def setup_cue_handler(osc_in):
    """Create an Execute DAT that handles incoming OSC messages from the hub."""
    project = op('/project1')

    handler = project.create(textDAT, "cue_handler")
    handler.nodeX = 500
    handler.nodeY = 0
    handler.comment = "Handles OSC messages from Production Hub"

    # The cue handler script that runs inside the Execute DAT
    handler.text = '''# Cue Handler - auto-generated by Event Template System
# Receives OSC from the Production Hub (after /td prefix is stripped).

# Static action map from hub_actions (address -> args)
ACTION_MAP = {
        # No TD cues defined in this template
    }

def onReceiveOSC(address, args):
    """Called when an OSC message is received from the hub."""
    # Camera switching: /camera/switch <index>
    if address == "/camera/switch":
        camera_index = int(args[0]) if args else 0
        op("video_switch").par.index = camera_index
        print(f"Camera switch -> {camera_index}")
        return

    # Check static action map
    if address in ACTION_MAP:
        print(f"Action: {address} {ACTION_MAP[address]}")
        return

    # Generic parameter control: /param/<name> <value>
    parts = address.strip("/").split("/")
    if len(parts) >= 2 and parts[0] == "param":
        param_name = parts[1]
        value = float(args[0]) if args else 0
        print(f"Param: {param_name} = {value}")
        return

    # Log unhandled messages
    print(f"OSC (unhandled): {address} {args}")
'''

    # Create Execute DAT to wire OSC input to handler
    exe = project.create(executeDAT, "osc_execute")
    exe.par.dat = osc_in
    exe.par.active = True
    exe.nodeX = 500
    exe.nodeY = 100
    exe.comment = "Triggers cue_handler on OSC input"

    print("Cue handler configured")
    return handler



# ============================================================
# OUTPUT PIPELINE
# ============================================================

def setup_output(switch):
    """Create the output pipeline from the video switch."""
    project = op('/project1')

    # Null TOP as a clean output reference point
    output = project.create(nullTOP, "program_output")
    switch.outputConnectors[0].connect(output)
    output.nodeX = switch.nodeX + 250
    output.nodeY = switch.nodeY
    output.comment = "Program output - connect to recording or streaming"

    # Info overlay for monitoring
    info = project.create(textTOP, "output_info")
    info.par.text = "PROGRAM OUTPUT"
    info.par.fontsizex = 20
    info.nodeX = output.nodeX
    info.nodeY = output.nodeY - 150
    info.comment = "Output status overlay"

    print("Output pipeline created")
    print("  Recording format: h264")
    print("  Target bitrate: 20Mbps")
    return output



# ============================================================
# MAIN - Run this to build the entire network
# ============================================================

def build_network():
    """Build the complete TouchDesigner network for this event."""
    print("")
    print("Building TouchDesigner network: Standard Recital")
    print("=======================================================")

    cameras = setup_cameras()
    switch = setup_switch(cameras)
    osc_in = setup_osc()
    setup_cue_handler(osc_in)
    output = setup_output(switch)

    print("")
    print("=======================================================")
    print("Network build complete!")
    print("  - Camera inputs are ready (assign physical devices)")
    print("  - Video switch is set to default camera")
    print("  - OSC input is listening for cue triggers")
    print("  - Program output is available at /project1/program_output")
    print("")
    print("Next steps:")
    print("  1. Verify camera device assignments in each Video Device In")
    print("  2. Test OSC input from QLab/Companion")
    print("  3. Connect program_output to your recording/streaming pipeline")
    print("")


# Run the build
build_network()
