#!/usr/bin/env python3
"""
QLab Cue Builder: Standard Recital
====================================
Auto-generated by the Production Event Template System.

This script connects to QLab via OSC and programmatically creates
all cues defined in the "standard_recital" event template.

Requirements:
    pip install python-osc

Usage:
    python standard_recital_qlab_cues.py [--host HOST] [--port PORT] [--passcode CODE]

IMPORTANT: Run this with QLab open and a workspace active.
The script will CREATE cues in the frontmost workspace.
"""

import argparse
import sys
import time

from pythonosc.udp_client import SimpleUDPClient


# --- Configuration ---
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 53000
DEFAULT_PASSCODE = "1234"

# Production Hub OSC target (where network cues send their messages)
HUB_HOST = "127.0.0.1"
HUB_PORT = 9000

# Delay between OSC commands (seconds) to let QLab process each one
CMD_DELAY = 0.1


# --- Helper Functions ---

def send(client: SimpleUDPClient, address: str, *args) -> None:
    """Send an OSC message and wait for QLab to process it."""
    if args and args[0] is not None:
        client.send_message(address, list(args))
    else:
        client.send_message(address, [])
    time.sleep(CMD_DELAY)


def connect_workspace(client: SimpleUDPClient, passcode: str) -> None:
    """Connect to the frontmost QLab workspace."""
    print(f"  Connecting to QLab workspace (passcode: {passcode})...")
    send(client, "/connect", passcode)
    time.sleep(0.5)


def new_cue(client: SimpleUDPClient, cue_type: str) -> None:
    """Create a new cue of the specified type. The new cue becomes selected."""
    send(client, "/new", cue_type)


def set_cue_property(client: SimpleUDPClient, prop: str, value) -> None:
    """Set a property on the currently selected cue."""
    send(client, f"/cue/selected/{prop}", value)


def move_cue_into_group(client: SimpleUDPClient, cue_number: str, group_number: str) -> None:
    """Move a cue into a group cue by number.

    Uses /move/{cue_id} with the group's cue_id as the target.
    QLab moves the cue to the END of the target group's children.
    The index argument 0 means "last position in group".
    """
    # /cue/{cue}/moveAfter/{target} — but the simplest reliable approach
    # is: select the cue, then use /move/selected to the group.
    # However, QLab's best-documented approach for OSC is:
    #   /move/{cue_number} {row_index}
    # where the cue is placed at row_index in the cue list, and if the
    # target row is inside a group, it goes into that group.
    #
    # The most reliable method: use /cue/{number}/parent to reparent directly.
    # This is a QLab 5 property: setting it to a group's cue_id moves the cue.
    send(client, f"/cue/{cue_number}/parent", group_number)


def create_group(client: SimpleUDPClient, name: str, number: str = "") -> None:
    """Create a group cue container."""
    new_cue(client, "group")
    set_cue_property(client, "name", name)
    if number:
        set_cue_property(client, "number", number)
    # Set group mode to "cue list" so it acts as a container
    set_cue_property(client, "mode", 0)
    print(f"  Created group: {name}")


def create_memo(client: SimpleUDPClient, name: str, notes: str = "") -> None:
    """Create a memo/placeholder cue."""
    new_cue(client, "memo")
    set_cue_property(client, "name", name)
    if notes:
        set_cue_property(client, "notes", notes)


def create_network_cue(
    client: SimpleUDPClient,
    name: str,
    number: str,
    osc_path: str,
    osc_args: list | None = None,
    dest_host: str = "",
    dest_port: int = 0,
    pre_wait: float = 0,
    post_wait: float = 0,
    color: str = "",
    notes: str = "",
) -> None:
    """Create a network cue that sends an OSC command to a target host."""
    new_cue(client, "network")
    set_cue_property(client, "name", name)
    set_cue_property(client, "number", number)
    # Configure as OSC message type
    set_cue_property(client, "messageType", 1)
    # Build the raw OSC string: address followed by args
    if osc_args:
        raw = osc_path + " " + " ".join(str(a) for a in osc_args)
    else:
        raw = osc_path
    set_cue_property(client, "rawString", raw)
    # Set destination host and port
    if dest_host:
        set_cue_property(client, "udpIP", dest_host)
    if dest_port:
        set_cue_property(client, "udpPort", dest_port)
    if pre_wait > 0:
        set_cue_property(client, "preWait", pre_wait)
    if post_wait > 0:
        set_cue_property(client, "postWait", post_wait)
    if color:
        set_cue_property(client, "colorName", color)
    if notes:
        set_cue_property(client, "notes", notes)
    print(f"  Created cue Q{number}: {name} -> {raw}")


def create_light_cue(
    client: SimpleUDPClient,
    name: str,
    number: str,
    fade_duration: float = 0,
    pre_wait: float = 0,
    color: str = "yellow",
    notes: str = "",
) -> None:
    """Create a lighting cue."""
    new_cue(client, "light")
    set_cue_property(client, "name", name)
    set_cue_property(client, "number", number)
    if fade_duration > 0:
        set_cue_property(client, "duration", fade_duration)
    if pre_wait > 0:
        set_cue_property(client, "preWait", pre_wait)
    set_cue_property(client, "colorName", color)
    if notes:
        set_cue_property(client, "notes", notes)
    print(f"  Created light cue Q{number}: {name}")


def build_show(client: SimpleUDPClient) -> None:
    """Build the complete cue list for: Standard Recital

    Two-pass build:
      Pass 1 - Create all groups and cues (flat, at root level)
      Pass 2 - Move cues into their parent groups
    """
    print("\nBuilding show: Standard Recital")
    print("==================================================")

    # ══════════════════════════════════════════════════
    # PASS 1: Create all groups and cues
    # (everything lands at the root level of the cue list)
    # ══════════════════════════════════════════════════
    print("\nPass 1: Creating cues...")

    # --- Group containers ---
    create_group(client, "PRE-SHOW", "G_PRE")
    create_group(client, "SHOW", "G_SHOW")
    create_group(client, "POST-SHOW", "G_POST")

    # --- Pre-Show Cues ---
    print("\n  Pre-Show cues:")
    create_network_cue(
        client,
        name="House to Half",
        number="010",
        osc_path="/lights/pb/1/1/level",
        osc_args=[0.5],
        dest_host=HUB_HOST,
        dest_port=HUB_PORT,
        post_wait=0,
        color="yellow",
        notes="Dim house lights to signal show starting",
    )

    create_network_cue(
        client,
        name="House Out",
        number="020",
        osc_path="/lights/pb/1/1/level",
        osc_args=[0.0],
        dest_host=HUB_HOST,
        dest_port=HUB_PORT,
        post_wait=5.0,
        color="yellow",
        notes="House lights out",
    )

    # --- Show Cues ---
    print("\n  Show cues:")
    create_network_cue(
        client,
        name="Stage Wash Up",
        number="030",
        osc_path="/lights/exec/1",
        osc_args=None,
        dest_host=HUB_HOST,
        dest_port=HUB_PORT,
        post_wait=2.0,
        color="yellow",
        notes="Bring up stage lighting",
    )

    # Q040: Mics Hot (2 hub actions)
    create_group(client, "Mics Hot", "040")
    set_cue_property(client, "mode", 4)  # fire all children
    set_cue_property(client, "colorName", "green")
    set_cue_property(client, "notes", "Open both lavalieres")

    create_network_cue(
        client,
        name="Mics Hot [1/2]",
        number="040.1",
        osc_path="/avantis/ch/1/mix/mute",
        osc_args=[0],
        dest_host=HUB_HOST,
        dest_port=HUB_PORT,
    )
    create_network_cue(
        client,
        name="Mics Hot [2/2]",
        number="040.2",
        osc_path="/avantis/ch/2/mix/mute",
        osc_args=[0],
        dest_host=HUB_HOST,
        dest_port=HUB_PORT,
    )


    # Q050: Camera 1 Live (2 hub actions)
    create_group(client, "Camera 1 Live", "050")
    set_cue_property(client, "mode", 4)  # fire all children
    set_cue_property(client, "colorName", "blue")
    set_cue_property(client, "notes", "Cut to wide shot")

    create_network_cue(
        client,
        name="Camera 1 Live [1/2]",
        number="050.1",
        osc_path="/obs/scene/Camera1",
        osc_args=None,
        dest_host=HUB_HOST,
        dest_port=HUB_PORT,
    )
    create_network_cue(
        client,
        name="Camera 1 Live [2/2]",
        number="050.2",
        osc_path="/cam1/preset/recall/1",
        osc_args=None,
        dest_host=HUB_HOST,
        dest_port=HUB_PORT,
    )


    create_network_cue(
        client,
        name="Recording Start",
        number="060",
        osc_path="/obs/record/start",
        osc_args=None,
        dest_host=HUB_HOST,
        dest_port=HUB_PORT,
        post_wait=0,
        color="purple",
        notes="Start audio and video recording",
    )

    # Q070: Camera 2 (2 hub actions)
    create_group(client, "Camera 2", "070")
    set_cue_property(client, "mode", 4)  # fire all children
    set_cue_property(client, "colorName", "blue")
    set_cue_property(client, "notes", "Cut to medium shot - operator triggered")

    create_network_cue(
        client,
        name="Camera 2 [1/2]",
        number="070.1",
        osc_path="/obs/scene/Camera2",
        osc_args=None,
        dest_host=HUB_HOST,
        dest_port=HUB_PORT,
    )
    create_network_cue(
        client,
        name="Camera 2 [2/2]",
        number="070.2",
        osc_path="/cam1/preset/recall/2",
        osc_args=None,
        dest_host=HUB_HOST,
        dest_port=HUB_PORT,
    )


    # Q080: Camera 1 (2 hub actions)
    create_group(client, "Camera 1", "080")
    set_cue_property(client, "mode", 4)  # fire all children
    set_cue_property(client, "colorName", "blue")
    set_cue_property(client, "notes", "Cut back to wide shot")

    create_network_cue(
        client,
        name="Camera 1 [1/2]",
        number="080.1",
        osc_path="/obs/scene/Camera1",
        osc_args=None,
        dest_host=HUB_HOST,
        dest_port=HUB_PORT,
    )
    create_network_cue(
        client,
        name="Camera 1 [2/2]",
        number="080.2",
        osc_path="/cam1/preset/recall/1",
        osc_args=None,
        dest_host=HUB_HOST,
        dest_port=HUB_PORT,
    )


    # --- Post-Show Cues ---
    print("\n  Post-Show cues:")
    create_network_cue(
        client,
        name="Recording Stop",
        number="090",
        osc_path="/obs/record/stop",
        osc_args=None,
        dest_host=HUB_HOST,
        dest_port=HUB_PORT,
        post_wait=0,
        color="purple",
        notes="Stop all recording",
    )

    # Q100: Mics Off (2 hub actions)
    create_group(client, "Mics Off", "100")
    set_cue_property(client, "mode", 4)  # fire all children
    set_cue_property(client, "colorName", "green")
    set_cue_property(client, "notes", "Mute both lavalieres")

    create_network_cue(
        client,
        name="Mics Off [1/2]",
        number="100.1",
        osc_path="/avantis/ch/1/mix/mute",
        osc_args=[1],
        dest_host=HUB_HOST,
        dest_port=HUB_PORT,
    )
    create_network_cue(
        client,
        name="Mics Off [2/2]",
        number="100.2",
        osc_path="/avantis/ch/2/mix/mute",
        osc_args=[1],
        dest_host=HUB_HOST,
        dest_port=HUB_PORT,
    )


    create_network_cue(
        client,
        name="House to Full",
        number="110",
        osc_path="/lights/pb/1/1/level",
        osc_args=[1.0],
        dest_host=HUB_HOST,
        dest_port=HUB_PORT,
        post_wait=0,
        color="yellow",
        notes="Bring house lights back up",
    )

    create_network_cue(
        client,
        name="Stage Blackout",
        number="120",
        osc_path="/lights/exec/2",
        osc_args=None,
        dest_host=HUB_HOST,
        dest_port=HUB_PORT,
        post_wait=0,
        color="yellow",
        notes="Fade stage lighting to black",
    )

    # ══════════════════════════════════════════════════
    # PASS 2: Move cues into their parent groups
    # Uses /cue/{number}/parent to reparent each cue
    # ══════════════════════════════════════════════════
    print("\nPass 2: Organizing cues into groups...")
    time.sleep(0.5)  # Let QLab finish processing all creates

    # Move sub-cues into their multi-action group cues
    move_cue_into_group(client, "040.1", "040")  # Mics Hot [1/2]
    move_cue_into_group(client, "040.2", "040")  # Mics Hot [2/2]
    move_cue_into_group(client, "050.1", "050")  # Camera 1 Live [1/2]
    move_cue_into_group(client, "050.2", "050")  # Camera 1 Live [2/2]
    move_cue_into_group(client, "070.1", "070")  # Camera 2 [1/2]
    move_cue_into_group(client, "070.2", "070")  # Camera 2 [2/2]
    move_cue_into_group(client, "080.1", "080")  # Camera 1 [1/2]
    move_cue_into_group(client, "080.2", "080")  # Camera 1 [2/2]
    move_cue_into_group(client, "100.1", "100")  # Mics Off [1/2]
    move_cue_into_group(client, "100.2", "100")  # Mics Off [2/2]

    # Move pre-show cues into PRE-SHOW group
    move_cue_into_group(client, "010", "G_PRE")  # House to Half
    move_cue_into_group(client, "020", "G_PRE")  # House Out
    print("  Moved 2 cues into PRE-SHOW")

    # Move show cues into SHOW group
    move_cue_into_group(client, "030", "G_SHOW")  # Stage Wash Up
    move_cue_into_group(client, "040", "G_SHOW")  # Mics Hot
    move_cue_into_group(client, "050", "G_SHOW")  # Camera 1 Live
    move_cue_into_group(client, "060", "G_SHOW")  # Recording Start
    move_cue_into_group(client, "070", "G_SHOW")  # Camera 2
    move_cue_into_group(client, "080", "G_SHOW")  # Camera 1
    print("  Moved 6 cues into SHOW")

    # Move post-show cues into POST-SHOW group
    move_cue_into_group(client, "090", "G_POST")  # Recording Stop
    move_cue_into_group(client, "100", "G_POST")  # Mics Off
    move_cue_into_group(client, "110", "G_POST")  # House to Full
    move_cue_into_group(client, "120", "G_POST")  # Stage Blackout
    print("  Moved 4 cues into POST-SHOW")

    print("\n==================================================")
    print("Show build complete! 12 cues organized into 3 groups.")
    print("  PRE-SHOW:  2 cues")
    print("  SHOW:      6 cues")
    print("  POST-SHOW: 4 cues")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Build QLab cues from event template"
    )
    parser.add_argument("--host", default=DEFAULT_HOST, help="QLab host IP")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT, help="QLab OSC port")
    parser.add_argument("--passcode", default=DEFAULT_PASSCODE, help="Workspace passcode")
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print what would be created without connecting to QLab"
    )
    args = parser.parse_args()

    if args.dry_run:
        print("DRY RUN - no OSC commands will be sent")
        print("(Use without --dry-run to build cues in QLab)")
        sys.exit(0)

    print(f"Connecting to QLab at {args.host}:{args.port}")
    client = SimpleUDPClient(args.host, args.port)
    connect_workspace(client, args.passcode)
    build_show(client)
    print("\nDone. Check QLab to verify cues were created correctly.")
